name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  NOTO_VERSION: ${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.HOMEBREW_TAP_TOKEN}}

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - run: bun install
        working-directory: packages/cli

      - name: Build
        working-directory: packages/cli
        run: bun run build

      - name: Determine npm tag
        id: determine_npm_tag
        shell: bash
        run: |
          if [[ "${{ env.NOTO_VERSION }}" =~ -(next|canary|beta|rc) ]]; then
            NPM_TAG=${BASH_REMATCH[1]}
          else
            git fetch origin main
            if git merge-base --is-ancestor "$GITHUB_SHA" origin/main; then
              NPM_TAG="latest"
            else
              echo "The tagged commit is not on the main branch."
              echo "::error ::Releases with the 'latest' npm tag must be on the main branch."
              exit 1
            fi
          fi
          echo "npm_tag=$NPM_TAG" >> $GITHUB_OUTPUT
          echo "Using npm tag: $NPM_TAG"

      - name: Publish to npm
        working-directory: packages/cli
        run: bun publish --provenance --access public --tag ${{ steps.determine_npm_tag.outputs.npm_tag }}
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

  homebrew:
    needs: release
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'next') && !contains(github.ref, 'canary') && !contains(github.ref, 'beta') && !contains(github.ref, 'rc')"
    steps:
      - name: Checkout homebrew-noto
        uses: actions/checkout@v4
        with:
          repository: snelusha/homebrew-noto
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Update Tap
        run: ruby scripts/release.rb "${{ env.NOTO_VERSION }}"

      - name: Commit Tap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_options: --gpg-sign=${{ steps.gpg.outputs.keyid }}
          commit_message: "chore: release ${{ env.NOTO_VERSION }}"
          commit_user_name: "snelusha"
          commit_user_email: "hello@snelusha.dev"
          commit_author: "Sithija Nelusha Silva <hello@snelusha.dev>"
